name: Python Function Action

on:
  schedule:
    - cron: '*/2 * * * *' # 每隔 2 分钟执行一次

jobs:
  run_function:
    name: Run Python Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.checkoutRef }}

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute Python function
        env:
          MY_BIS_KEY: ${{ secrets.MY_BIS_KEY }}
        run: python bis_get_floor_price.py
