name: Python Function Action

on:
  schedule:
    - cron: '*/2 * * * *' # 每隔 2 分钟执行一次

jobs:
  run_function:
    name: Run Python Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute Python function
        env:
          MY_BIS_KEY: ${{ secrets.MY_BIS_KEY }}
        run: python bis_get_floor_price.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"
          git add floor_prices.json
          git commit -m "Update floor_prices.json"
          git push origin HEAD:main
        env:
          MY_BIS_KEY: ${{ secrets.MY_BIS_KEY }}
